-- 建表语句
CREATE TABLE `bns_equip_item` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`equip_id` BIGINT(20)  DEFAULT NULL  COMMENT '装备ID',
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '名称',
`parent_id` BIGINT(20)  DEFAULT NULL  COMMENT '父级',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `bns_equip_item` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `bns_equip_item` ADD COLUMN equip_id BIGINT(20)  DEFAULT NULL  COMMENT '装备ID';
ALTER TABLE `bns_equip_item` ADD COLUMN name VARCHAR(32)  DEFAULT NULL  COMMENT '名称';
ALTER TABLE `bns_equip_item` ADD COLUMN parent_id BIGINT(20)  DEFAULT NULL  COMMENT '父级';

