-- 建表语句
CREATE TABLE `bns_equip` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '名称',
`type` INTEGER(11)  DEFAULT NULL  COMMENT '类型【】',
`parent_id` BIGINT(20)  DEFAULT NULL  COMMENT '父级',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `bns_equip` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `bns_equip` ADD COLUMN name VARCHAR(32)  DEFAULT NULL  COMMENT '名称';
ALTER TABLE `bns_equip` ADD COLUMN type INTEGER(11)  DEFAULT NULL  COMMENT '类型【】';
ALTER TABLE `bns_equip` ADD COLUMN parent_id BIGINT(20)  DEFAULT NULL  COMMENT '父级';

