-- 建表语句
CREATE TABLE `bns_star` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`star` INTEGER(11)  DEFAULT NULL  COMMENT '星级',
`exp` INTEGER(11)  DEFAULT NULL  COMMENT '经验',
`remark` VARCHAR(32)  DEFAULT NULL  COMMENT '备注',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `bns_star` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `bns_star` ADD COLUMN star INTEGER(11)  DEFAULT NULL  COMMENT '星级';
ALTER TABLE `bns_star` ADD COLUMN exp INTEGER(11)  DEFAULT NULL  COMMENT '经验';
ALTER TABLE `bns_star` ADD COLUMN remark VARCHAR(32)  DEFAULT NULL  COMMENT '备注';

