-- 建表语句
CREATE TABLE `ppsg_level` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '名称',
`combat` INTEGER(11)  DEFAULT NULL  COMMENT '战力',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `ppsg_level` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `ppsg_level` ADD COLUMN name VARCHAR(32)  DEFAULT NULL  COMMENT '名称';
ALTER TABLE `ppsg_level` ADD COLUMN combat INTEGER(11)  DEFAULT NULL  COMMENT '战力';

