-- 建表语句
CREATE TABLE `bns_equip_material` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '材料名称',
`count` INTEGER(11)  DEFAULT NULL  COMMENT '材料数量',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `bns_equip_material` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `bns_equip_material` ADD COLUMN name VARCHAR(32)  DEFAULT NULL  COMMENT '材料名称';
ALTER TABLE `bns_equip_material` ADD COLUMN count INTEGER(11)  DEFAULT NULL  COMMENT '材料数量';

