-- 建表语句
CREATE TABLE `bns_material` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '材料名称',
`image` VARCHAR(32)  DEFAULT NULL  COMMENT '材料图片',
`price` DECIMAL(11,2)  DEFAULT NULL  COMMENT '材料价格',
`create_time` datetime  DEFAULT NULL  COMMENT '创建时间',
`del_flag` TINYINT(1)  DEFAULT NULL  COMMENT '删除标识【0：未删除，1：已删除】',
`type` INTEGER(11)  DEFAULT NULL  COMMENT '材料类型【0：材料 1：装备】',
`num` INTEGER(11)  DEFAULT NULL  COMMENT '封印符数量',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `bns_material` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `bns_material` ADD COLUMN name VARCHAR(32)  DEFAULT NULL  COMMENT '材料名称';
ALTER TABLE `bns_material` ADD COLUMN image VARCHAR(32)  DEFAULT NULL  COMMENT '材料图片';
ALTER TABLE `bns_material` ADD COLUMN price DECIMAL(11)  DEFAULT NULL  COMMENT '材料价格';
ALTER TABLE `bns_material` ADD COLUMN create_time datetime  DEFAULT NULL  COMMENT '创建时间';
ALTER TABLE `bns_material` ADD COLUMN del_flag TINYINT(1)  DEFAULT NULL  COMMENT '删除标识【0：未删除，1：已删除】';
ALTER TABLE `bns_material` ADD COLUMN type INTEGER(11)  DEFAULT NULL  COMMENT '材料类型【0：材料 1：装备】';
ALTER TABLE `bns_material` ADD COLUMN num INTEGER(11)  DEFAULT NULL  COMMENT '封印符数量';

